name: sajaya_general_app
description: "A new Flutter project. flutter version 3.19.5"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter_localizations:
    sdk: flutter
  encrypt: ^5.0.1
  flutter_slidable: ^3.0.0
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.0.9
  intl: ^0.18.0-nullsafety.1 
  dio: ^4.0.4
  get_it: ^7.6.0
  keyboard_actions: ^3.3.1+1
  badges: ^3.1.1
  multi_select_flutter: ^4.1.3
  geolocator: ^7.0.0
  permission_handler: ^10.4.3
  image_picker: ^0.8.4+4
  stop_watch_timer: ^3.0.1
  record: ^4.4.4
  just_audio: ^0.9.38
  video_thumbnail: ^0.5.3
  open_file: ^3.3.2
  file_picker: ^5.3.3
  video_compress: ^3.1.2
  call_log: ^4.0.0
  connectivity_plus: ^6.0.2
  flutter_local_notifications: ^17.1.0
  wheel_slider: ^1.2.1
  flutter_image_compress: ^2.2.0
  numberpicker: ^2.1.2
  trust_location: ^2.0.13
  device_info_plus: ^10.1.0
  path_provider: ^2.1.3
  signature: ^5.5.0
  flutter_pdfview: ^1.3.2
  pdf: ^3.11.0
  sizer: ^2.0.15
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/images/maintenance/
    
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
        - asset: assets/fonts/NotoKufiArabic-ExtraBold.ttf
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
        
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf